### ISSUE TITLE
Garbage created after running lwatch

### ISSUE THREAD

**Issue by brunobasto** [brunobasto/liferay-watch#6]
<img width="522" alt="screen shot 2017-07-04 at 12 22 43 pm" src="https://user-images.githubusercontent.com/156388/27835948-966018ee-60b3-11e7-8ce3-8a75c21eb61c.png">

**Comment by drewbrokke** [comment]
This could work as a very fast approach, if you haven't settled on one yet ;) 

`git ls-files --others --exclude-standard`

Though I guess the challenge is to make sure you don't clear out files you intend to continue working on but have not committed yet.

**Comment by brunobasto** [comment]
Hey drew, thanks for chiming in. Yeah, that could be dangerous. I'm trying to figure this out right now and looks like the bad guy is this line: https://github.com/brunobasto/liferay-watch/blob/master/tasks/javascript.js#L25

Though removing it makes the amd transpiler translate imports wrongly.

**Comment by brunobasto** [comment]
One way to go about it would be to remove those files after the transpiler is done.. Though it feels there should probably be a better way of doing this. I'll take a look again on how gradle calls metal-cli for the portal transpileJS task to make it work

**Comment by brunobasto** [comment]
moved to https://github.com/liferay/liferay-osgi-watch/issues/14
